name: Autonomous Robotic Sample Handling
view: Tab # Tab or Popup if has an GUI

acquisition_modes: 
  - name: Plugin Acquisition
    file_name: plugin_acquisition_mode.py

###################################################################
# how to add plugin device in the .navigate/configuration.yaml file
#
# robot_arm:
#   hardware:
#     type: PluginDevice
###################################################################