#Info necessary for each hardware
environment:
#microscope is the center of the environement
  robot:
    #robot base is the reference
    position: [0,0,0]
    robot_base_plate_height: 9.77
  motor: 
    units: 19
  components:
    vial_height_from_carousel: 86.06
    carousel_height_from_table: 60.45
    vial_attack_distance_from_carousel: 193.294
    trf_from_wrf_cartesian: [190,0,308,0,90,0]
    trf_to_gripper_edge: 59
    trf_to_gripper_bottom: 22.14
    MEPG_thickness: 18.14
    tolerance_up: 8
    tolerance_forward: 8
    



